backend/socialDistribution/project/urls.py
from django.urls import path
from . import views

app_name = "project"
urlpatterns = [
    path("create-post", views.CreatePostView.as_view(), name="create-post"),
    path("edit-post/<str:pk>", views.EditPostView.as_view(), name="edit-post"),
    # Stream
    path("<str:username>/stream", views.StreamView.as_view(), name="stream"),
    # Author
    path("<str:pk>", views.AuthorView.as_view(), name="author"),
    # Post
    path("posts/<str:pk>", views.PostView.as_view(), name="post"),
    # Profile
    path("<str:pk>/profile", views.ProfileView.as_view(), name="profile"),
    # Edit Profile
    path("edit/", views.profile_edit, name="profile_edit"),
    # Homepage
    path("", views.stream_view, name="home"),
    # Signup
    path("signup/", views.SignupView.as_view(), name="signup"),
    # API
    path("api/authors/", views.AuthorAPIView.as_view(), name="get_authors"),
    path("api/authors/<str:pk>/", views.update_author, name="author_api"),
    path("api/authors/<str:pk>/posts/", views.new_post_api, name="new_post_api"),
    path(
        "api/authors/<str:pk>/posts/<str:post_id>",
        views.update_post_api,
        name="update_post_api",
    ),
    path("api/authors/<str:pk>/inbox", views.update_inbox, name="inbox_api"),
    path("api/nodes/", views.NodeAPIView.as_view(), name="node_api"),
    # Likes
    path("post/<str:pk>/like/", views.like_post, name="like_post"),
    # Comments
    path("post/<str:pk>/comment/", views.add_comment, name="add_comment"),
    # Follow
    path("author/<str:pk>/follow/", views.send_follow_request, name="follow"),
    # Accept follow request
    path(
        "followrequest/<str:pk>/accept/",
        views.accept_follow_request,
        name="accept_follow",
    ),
    # Decline follow request
    path(
        "followrequest/<str:pk>/decline/",
        views.decline_follow_request,
        name="decline_follow",
    ),
    # Decline follow request
    path("author/<str:pk>/unfollow/", views.unfollow, name="unfollow"),
    path("search/", views.SearchAuthors.as_view(), name="search"),
    # Follow API
    path(
        "api/authors/<str:pk>/followers/",
        views.FollowersAPIView.as_view(),
        name="get_followers",
    ),
    path(
        "api/authors/<str:pk>/followers/<str:follower_id>",
        views.FollowerAPIView.as_view(),
        name="api_follower",
    ),
    path(
        "api/authors/<str:pk>/inbox/followrequest",
        views.FollowRequestAPIView.as_view(),
        name="api_follow_request",
    ),
    path("post/<str:pk>/delete", views.delete_post, name="post_delete"),
]

backend/socialDistribution/socialDistribution/urls.py
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("project/", include("project.urls")),
    path("admin/", admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("", include("django.contrib.auth.urls")),
]

backend/socialDistribution/project/models.py
from django.db import models
import uuid
from datetime import datetime
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    url = models.URLField(max_length=200, blank=True, null=True)
    host = models.GenericIPAddressField(
        default="127.0.0.1"
    )  # TODO add conditional for localhost if not deployed
    displayName = models.CharField(max_length=50)
    github = models.URLField(max_length=200, blank=True)
    profileImage = models.URLField(
        max_length=200, default="https://i.imgur.com/k7XVwpB.jpeg"
    )

    bio = models.CharField(max_length=1000, blank=True)

    streamPosts = models.ManyToManyField("Post", related_name="inboxes", blank=True)
    following = models.ManyToManyField(
        "Author", related_name="followers", symmetrical=False, blank=True
    )


class FollowRequest(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    summary = models.CharField(max_length=200)
    follower = models.ForeignKey(
        Author, related_name="outgoing_follow_requests", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        Author, related_name="incoming_follow_requests", on_delete=models.CASCADE
    )


class Post(models.Model):
    class VisibilityChoice(models.TextChoices):
        PUBLIC = "PUBLIC", "PUBLIC"
        PRIVATE = "PRIVATE", "PRIVATE"
        FRIENDS_ONLY = "FRIENDS_ONLY", "FRIENDS_ONLY"

    title = models.CharField(max_length=50, default="Untitled")
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    source = models.URLField(max_length=200)
    origin = models.URLField(max_length=200)
    description = models.CharField(max_length=50, default="")
    contentType = models.CharField(max_length=200)
    content = models.TextField(max_length=600)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categories = models.CharField(max_length=200, default="")  # TODO Change to list
    count = models.IntegerField(default=0)
    published = models.DateTimeField(default=datetime.now, blank=True)
    visibility = models.CharField(
        max_length=50, choices=VisibilityChoice.choices, default=VisibilityChoice.PUBLIC
    )
    unlisted = models.BooleanField()

    def get_absolute_url(self):
        return reverse("project:post", kwargs={"pk": self.pk})


class Comment(models.Model):
    # TODO needs a foreign key for Post
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.TextField(max_length=600)
    contentType = models.CharField(max_length=200)
    published = models.DateTimeField(default=datetime.now, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class PostLike(models.Model):
    context = models.URLField(max_length=200)
    summary = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class CommentLike(models.Model):
    context = models.URLField(max_length=200)
    summary = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class Node(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nodeName = models.CharField(max_length=50)
    apiURL = models.URLField(max_length=200)
    host = models.GenericIPAddressField(default="127.0.0.1:8000")

backend/socialDistribution/project/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import AuthorCreationForm, EditProfileForm, CreatePostForm, EditPostForm
from .models import Author, Post, Comment, PostLike, FollowRequest, Node
from .serializers import (
    PostSerializer,
    AuthorSerializer,
    NodeSerializer,
    FollowRequestSerializer,
)


class AuthorView(generic.DetailView):
    template_name = "project/author.html"
    model = Author


class PostView(generic.DetailView):
    template_name = "project/post.html"
    model = Post


class StreamView(generic.ListView):
    template_name = "project/stream.html"
    context_object_name = "latest_posts"

    def get_queryset(self):
        self.author = get_object_or_404(Author, displayName=self.kwargs["username"])
        return self.author.streamPosts.order_by("-published")


def stream_view(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("login"))

    author = request.user.author
    latest_posts = author.streamPosts.order_by("-published")

    # Fetch friend requests
    friend_requests = FollowRequest.objects.filter(following=author)

    context = {
        "latest_posts": latest_posts,
        "friend_requests": friend_requests,
    }
    return render(request, "project/stream.html", context)


class ProfileView(generic.DetailView):
    template_name = "project/profile.html"
    model = Author


@login_required
def profile_edit(request):
    # Edit the current user's profile
    logged_in_author = request.user.author

    if request.method == "GET":
        form = EditProfileForm(instance=logged_in_author)
        return render(request, "project/edit_profile.html", {"form": form})
    elif request.method == "POST":
        form = EditProfileForm(request.POST, instance=logged_in_author)

        # Given the navigation bar, no redirection is needed.
        if form.is_valid():
            if form.has_changed():
                form.save()

                # Only display notification if some changes were made
                messages.success(request, "Changes saved successfully")
            return HttpResponseRedirect(reverse("project:profile_edit"))
        else:
            # if the form input was not valid, try again
            messages.success(
                request, "Warning: not a valid Github link, changes discarded"
            )
            return HttpResponseRedirect(reverse("project:profile_edit"))


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "project/create-post.html"
    form_class = CreatePostForm
    login_url = "login"

    def form_valid(self, form):
        author = get_object_or_404(Author, pk=self.request.user.author.id)
        form.instance.author = author

        # TODO These are just placeholders. Need to figure out what to put here for part 2
        form.instance.source = "http://127.0.0.1:8000/"
        form.instance.origin = "http://127.0.0.1:8000/"

        form.instance.contentType = (
            "text/plain"  # TODO Change when implementing Markdown
        )
        form.instance.count = 0
        form.instance.published = datetime.now()

        return super(CreatePostView, self).form_valid(form)


# https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-editing/#django.views.generic.edit.UpdateView
class EditPostView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = "project/edit-post.html"
    form_class = EditPostForm
    login_url = "login"

    # TODO check that the author is the current user


class SignupView(generic.CreateView):
    # Use custom form to connect author model to user creation
    form_class = AuthorCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

    # Send a success notification to the redirected page (login page)
    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
            "Account created. An admin will activate your account shortly.",
        )
        return HttpResponseRedirect(reverse("login"))


class AuthorAPIView(APIView):
    """
    Get the list of authors on our website
    """

    def get(self, request, *args, **kwargs):
        authors = Author.objects.all()
        serializer = AuthorSerializer(authors, many=True)
        full_response = {"type": "authors", "items": serializer.data}
        return Response(full_response)


@api_view(["GET", "POST"])
def update_author(request, pk):
    """
    Update or get a specific author
    """
    author = get_object_or_404(Author, id=pk)

    if request.method == "GET":
        serializer = AuthorSerializer(author, data=request.data, partial=True)
        if serializer.is_valid():
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)
    if request.method == "POST":
        serializer = AuthorSerializer(author, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)


@api_view(["GET", "POST"])
def new_post_api(request, pk):
    posts = Post.objects.filter(author=pk)

    if request.method == "GET":
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    if request.method == "POST":
        serializer = PostSerializer(posts, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)


@api_view(["GET", "POST", "DELETE", "PUT"])
def update_post_api(request, pk, post_id):
    if request.method == "PUT":
        serializer = PostSerializer(data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)

    post = get_object_or_404(Post, id=post_id)

    if request.method == "GET":
        serializer = PostSerializer(post, data=request.data, partial=True)
        if serializer.is_valid():
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)
    if request.method == "POST":
        serializer = PostSerializer(post, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)
    elif request.method == "DELETE":
        post.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(["GET", "POST", "DELETE"])
def update_inbox(request, pk):
    """
    Update an inbox
    """
    author = get_object_or_404(Author, id=pk)
    inbox = author.streamPosts.all()

    if request.method == "GET":
        serializer = PostSerializer(inbox, many=True)
        author_str = "http://" + str(author.host) + "/authors/" + str(author.id)
        full_response = {
            "type": "inbox",
            "author": author_str,
            "items": serializer.data,
        }
        return Response(full_response, status=201)

    if request.method == "POST":
        # TODO: if the type is not "post", then check for comments/likes/follows
        serializer = PostSerializer(author, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(status=400, data=serializer.errors)
    elif request.method == "DELETE":
        author.streamPosts.remove()
        return Response(status=status.HTTP_204_NO_CONTENT)


class NodeAPIView(APIView):
    """
    Get the list of nodes
    """

    def get(self, request, *args, **kwargs):
        nodes = Node.objects.all()
        serializer = NodeSerializer(nodes, many=True)
        return Response(serializer.data)


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        content = request.POST.get("content")
        Comment.objects.create(
            author=request.user.author,
            post=post,
            comment=content,
            contentType="text/plain",
        )  # Assuming contentType is plain text for this example
    return HttpResponseRedirect(reverse("project:post", args=[pk]))


@login_required
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # Check if the user already liked the post
    liked = PostLike.objects.filter(author=request.user.author, post=post).exists()
    if not liked:
        PostLike.objects.create(
            author=request.user.author,
            post=post,
            summary=f"{request.user.username} likes this",
            context=post.source,
        )
    else:
        PostLike.objects.filter(author=request.user.author, post=post).delete()
    return HttpResponseRedirect(reverse("project:post", args=[pk]))


# TODO none of these login decerators check who is logged in. anybody can accept requests on other people's behalfs right now.


@login_required
def send_follow_request(request, pk):
    author = get_object_or_404(Author, pk=pk)
    if request.method == "POST":

backend/socialDistribution/project/templates/project/create-post.html
{% extends "base.html" %}

{% block title %}Create Post{% endblock %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">

<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" value="Submit">Create</button>
</form>
{% endblock %}

backend/socialDistribution/project/templates/project/edit-post.html
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">

<h1>Edit Post</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" value="Submit">Submit</button>
</form>

backend/socialDistribution/project/templates/project/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <!-- The following are examples to reference user and author data. -->
    <div class="task_bar">
      <div>
          <button type="button" id="search">
              <a id="search_a" href="{% url 'project:search' %}">Search</a>
            </button>
            <button type="button" id="profile">
              <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
            </button>
            <button type="button" id="post">
              <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
            </button>
            <button type="button" id="home">
              <a id="home_a"href="{% url 'project:home' %}">Home</a>
              </button>
      </div>
      <div class="right_nav">
          <button type="button" id="settings">
              <a id="set_a">Settings</a>
          </button>
          <button type="button" id="logout">
              <a id="log_a" href="{% url 'logout' %}">Logout</a>
          </button>
          
      </div>
    </div>
  <h1>Hi {{ user.username }}!</h1>
  <h1>Hi {{ user.author.displayName }}!</h1>
  <h1>Check me out on Github: {{ user.author.github }}</h1>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

backend/socialDistribution/project/templates/project/post.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<div class="post-popup">
    <h1>{{ post.title }}</h1>
   
    <h3><a href="{% url 'project:profile' post.author.id %}">{{ post.author.displayName }}</a></h3>
    <p>{{ post.content }}</p>

    <p>{{ post.postlike_set.count }} &#x1F44D; {{ post.comment_set.count }} &#128172;</p>

    <!-- Like Button -->
    <form method="post" action="{% url 'project:like_post' post.id %}">
        {% csrf_token %}
        <button type="submit">Like</button>
    </form>

    <!-- Update Post -->
    {% if user.is_authenticated and user.author.id == post.author.id%}
        <form action="{% url 'project:edit-post' post.id %}">
            <button type="submit">Edit Post</button>
        </form>
    {% endif %}

    <h2>Comments</h2>

    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all %}
            <div class="comment">
                <h3><a href="{% url 'project:profile' comment.author.id %}">{{ comment.author.displayName }}</a></h3>
                <p>{{ comment.comment }}</p>

                <p>{{ comment.commentlike_set.count }} &#x1F44D;</p>
            </div>
        {% endfor %}
    {% else %}
        <p>No comments are available.</p>
    {% endif %}

    <!-- Comment Form -->
    <form method="post" action="{% url 'project:add_comment' post.id %}">
        {% csrf_token %}
        <textarea name="content" placeholder="Add a comment..."></textarea>
        <button type="submit">Comment</button>
    </form>
    <form method="post" action="{% url 'project:post_delete' post.id %}">
        {% csrf_token %}
    {%if post.author.id == user.author.id%}
    <button type="submit">DELETE</button>
    {%endif%}
    </form>
</div>
{% endblock %}

backend/socialDistribution/project/templates/project/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}


<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<div class = "user-profile">
    <!-- Note: remove hardcoded properties for image -->
    
    <img src={{ author.profileImage }} alt="user profile image" width="100" height="100">

        <h1 id = "disp">{{ author.displayName }}</h1>
        <a id="git" href="http://{{ author.github }}">Check me out on Github</a>
    
        <h4 id="bio">{{ author.bio }}</h4>    


</div>

<br></br>

<div class = "posts">
    <h4>Posts</h4>
    {% if author.post_set.all %}
    <ul>
    {% for post in author.post_set.all %}
        <li class="post">
            <h3><a href="{% url 'project:post' post.id %}">{{ post.title }}</a></h3>

            <p>{{ post.content }}</p>

            <p>{{ post.postlike_set.count }} &#x1F44D {{ post.comment_set.count }} &#128172</p>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}
</div>
<h4> Followers:</h4>
<div class = "followers">
    <ul>
        {% for follow in author.followers.all %}
    <li>
        <a href="{% url 'project:profile' follow.id %}">{{follow.displayName}}</a>
    </li>
    {%endfor%}
    </ul>
    
</div>

<div class = "github-activity">
    <h4>Github Activity</h4>
</div>

<form method="post" action="{% url 'project:follow' author.id %}">
    {% csrf_token %}
    {% if user.is_authenticated %}
    {% if author.displayName != user.author.displayName %}
    <button type="submit">Follow</input>
    {%endif%}
    {%endif%}
</form>

 {% endblock %}

backend/socialDistribution/project/templates/project/search-page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- reference https://www.youtube.com/watch?v=VL5ZNCjXEbw -->
<head>
    <link rel="stylesheet" href="{% static 'project/base.css' %}">
</head>
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>

<h1>Search for Users</h1>
<br>

<body>
<form action="{% url 'project:search' %}" method="get">
    {% csrf_token %}
    <input name = "username" type="text" placeholder = "Type here..." >
    <button type="submit">Search</button>
</form>

    <br>
    <div id = 'display_user_search'>
    <h4 id="user_title">
        Users:
    </h4>
    {% if userlist %}
    {% for user in userlist %}
    
        <li style="list-style-type:none">
            <a href="{% url 'project:profile' user.id %}">{{ user.displayName }}</a>
        </li>
    {% endfor %}
    {%else%}
        <p> There are no matching users, try again.</p>
    {%endif%}
</div>


    
    
</body>
{% endblock %}
    <!-- <a href="search/">Click to Search</a>> -->

backend/socialDistribution/project/templates/project/stream.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'project/base.css' %}">
<div class="task_bar">
    <div>
        <button type="button" id="search">
            <a id="search_a" href="{% url 'project:search' %}">Search</a>
          </button>
          <button type="button" id="profile">
            <a id="prof_a" href="{% url 'project:profile' pk=user.author.id %}">Profile</a>
          </button>
          <button type="button" id="post">
            <a id="post_a"href="{% url 'project:create-post' %}">Create a Post</a>
          </button>
          <button type="button" id="home">
            <a id="home_a"href="{% url 'project:home' %}">Home</a>
            </button>
    </div>
    <div class="right_nav">
        <button type="button" id="settings">
            <a id="set_a">Settings</a>
        </button>
        <button type="button" id="logout">
            <a id="log_a" href="{% url 'logout' %}">Logout</a>
        </button>
        
    </div>
  </div>
<h1>Stream/Inbox Page</h1>

  

<div class="user-profile">
    <img src={{ author.profileImage }} alt="User Image">
    <div class="user-details">
        <h2 id="stream-name">{{user.author.displayName}}</h2>
        <p>Welcome to SocialDistribution! Make posts, explore other user profiles, and make friends.</p>
        <button>Settings</button>
    </div>
</div>

<div class="user-posts">
    {% if latest_posts %}
        {% for post in latest_posts %}
            <div class="post">
                <h3><a href="{% url 'project:post' post.id %}">{{ post.title }}</a></h3>
                <p>{{ post.content }}</p>
                <p>{{ post.postlike_set.count }} &#x1F44D; {{ post.comment_set.count }} &#128172;</p>
            </div>
        {% endfor %}
    {% else %}
        <p>There is no activity in your feed...</p>
    {% endif %}
</div>


<div class="inbox">
    <h2>Inbox</h2>
    <!-- Friend request processing -->
    <h3>Friend Requests</h3>
    <ul>
        {% for fr in user.author.incoming_follow_requests.all %}
            <li>
                {{ fr.follower.displayName }} wants to follow you. 
    
                <!-- Accept Follow Form -->
                <form method="post" action="{% url 'project:accept_follow' fr.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Accept</button>
                </form> |
    
                <!-- Decline Follow Form -->
                <form method="post" action="{% url 'project:decline_follow' fr.pk %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Decline</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    
</div>
{% endblock %}